# Generated by Django 4.1.3 on 2023-06-15 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_cl', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ControlledBridgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DriveAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Forklift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_serial_number', models.CharField(max_length=32)),
                ('engine_serial_number', models.CharField(max_length=32)),
                ('transmission_serial_number', models.CharField(max_length=32)),
                ('drive_axle_serial_number', models.CharField(max_length=32)),
                ('controlled_bridge_serial_number', models.CharField(max_length=32)),
                ('delivery_contract', models.CharField(max_length=32)),
                ('date_of_shipment', models.DateField()),
                ('end_user', models.CharField(max_length=32)),
                ('delivery_address', models.CharField(max_length=32)),
                ('equipment', models.CharField(max_length=32)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklift.client')),
                ('controlled_bridge_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklift.controlledbridgemodel')),
                ('drive_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklift.driveaxlemodel')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklift.enginemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NatureRefusal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='To',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('operating', models.PositiveIntegerField(default=0)),
                ('orders_number', models.CharField(max_length=32)),
                ('orders_date', models.DateField()),
                ('organization', models.CharField(max_length=32)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklift.forklift')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklift.service_company')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklift.typeto')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='forklift',
            name='model_equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklift.modelequipment'),
        ),
        migrations.AddField(
            model_name='forklift',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklift.service_company'),
        ),
        migrations.AddField(
            model_name='forklift',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklift.transmissionmodel'),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_date', models.DateField()),
                ('operating', models.PositiveIntegerField(default=0)),
                ('order_description', models.TextField()),
                ('used_spare_parts', models.TextField()),
                ('recovery_date', models.DateField()),
                ('downtime', models.IntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklift.forklift')),
                ('order_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklift.naturerefusal')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklift.recoverymethod')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forklift.service_company')),
            ],
            options={
                'ordering': ['-orders_date'],
            },
        ),
    ]
