# Generated by Django 4.1.3 on 2023-06-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift', '0002_alter_client_title_alter_client_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forklift',
            name='delivery_address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='forklift',
            name='equipment',
            field=models.CharField(max_length=256),
        ),
    ]
